export const IPC_CHANNELS = {
  getSnapshot: "workspace:get-snapshot",
  selectProjectDirectory: "workspace:select-project-directory",
  updateProject: "workspace:update-project",
  removeProject: "workspace:remove-project",
  selectClaudeExecutable: "workspace:select-claude-executable",
  autoDetectClaudeExecutable: "workspace:auto-detect-claude-executable",
  updateWeComConfig: "workspace:update-wecom-config",
  upsertAutomationJob: "workspace:upsert-automation-job",
  upsertAutomationWeComBot: "workspace:upsert-automation-wecom-bot",
  deleteAutomationWeComBot: "workspace:delete-automation-wecom-bot",
  updateAutomationWeComGroupAlias:
    "workspace:update-automation-wecom-group-alias",
  deleteAutomationJob: "workspace:delete-automation-job",
  runAutomationJob: "workspace:run-automation-job",
  retryAutomationRun: "workspace:retry-automation-run",
  cancelAutomationRun: "workspace:cancel-automation-run",
  createSession: "workspace:create-session",
  restartSession: "workspace:restart-session",
  renameSession: "workspace:rename-session",
  removeSession: "workspace:remove-session",
  stopSession: "workspace:stop-session",
  readClipboardText: "workspace:read-clipboard-text",
  writeClipboardText: "workspace:write-clipboard-text",
  showSessionNotification: "workspace:show-session-notification",
  writeTerminal: "workspace:write-terminal",
  resizeTerminal: "workspace:resize-terminal",
  getTerminalSnapshot: "workspace:get-terminal-snapshot",
  listWorkspaceChanges: "workspace:list-changes",
  readWorkspaceFile: "workspace:read-file",
  terminalData: "workspace:terminal-data",
  sessionChanged: "workspace:session-changed",
  wecomStateChanged: "workspace:wecom-state-changed",
  automationStateChanged: "workspace:automation-state-changed",
} as const;
